site_name: HyPyP Docs

markdown_extensions:
  - admonition
  - codehilite
  - markdown_include.include

theme:
  name: "material"

extra_css:
  - custom.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      watch:
        - hypyp
